### ISSUE TITLE
private APIのtradeで”nonce not incremented”のエラーが出る

### ISSUE THREAD

**Issue by ttskmnj** [techbureau/zaifbot#11]

**Comment by ttskmnj** [comment]
毎回ではありませんが時々、private APIのtradeを実行した際に”nonce not incremented”のエラーが出ます。
nonceってprivate APIが自動でリセットしてると思うんですけど、呼び出し側で指定することって出来ますか？

**Comment by Akira-Taniguchi** [comment]
ZaifPrivateApiのコンストラクタで指定可能です。
ただ、ちょっと使いにくいので、ちょっと修正します。

**Comment by Akira-Taniguchi** [comment]
@RossyWhite 
このあたり、zaifapiの修正も考慮したほうがシンプルにじっそうできると思うので、
手を付ける前に一旦相談してください。

**Comment by Akira-Taniguchi** [comment]
zaifapiを修正したので、このissueは閉じます
