### ISSUE TITLE
api.pyでエラーをraiseしているが、exceptでキャッチしていないためプロセスが止まる

### ISSUE THREAD

**Issue by ttskmnj** [techbureau/zaifbot#12]
api.pyの60行目でエラーをraiseしているのですが、exceptでキャッチしていないためプロセスが止まってしまってます。
このクラスは最新値取得で使われてると思うのですが、エラーががあって最新値取得が取れなくても、また次回取得すれば良いので、プロセスを止めない様にexceptでキャッチして処理してもらえませんか。

**Comment by Akira-Taniguchi** [comment]
すみません、あれからソース変わってしまったので、最新ソースでいうところのどこか等教えていただければ。
お手数おかけします。
@ttskmnj

**Comment by ttskmnj** [comment]
最新ソースですとlast_price.pyの３８行目のraise ZaifBotError('thread is dead')のところです。
@Akira-Taniguchi
