### ISSUE TITLE
[質問] 売りー逆指定買いを固定値ではなく、動的に買いを行う方法はすでにありますか？

### ISSUE THREAD

**Issue by naokits** [techbureau/zaifbot#121]
売りー逆指定買い（指値）はtrade APIで提供されていますが、指値ではなく、例えば売った金額より安くなったらすぐに買うなどの要望があると思います。
自分は、独自にこの機能を実装していますが、本ライブラリではすでにそのような機能を提供しておられますでしょうか？

**Comment by RossyWhite** [comment]
質問ありがとうございます。

現在はまだそのような機能はございませんが、
今ちょうど注文のロジックを整備し始めておりますので、その際に参考にさせていただきます。

**Comment by RossyWhite** [comment]
別で立てていただいたissueも参考にさせておりますので、
また何かあればお気軽にお願いします。

**Comment by RossyWhite** [comment]
クローズしますね。
何かあれば別のissue立ててください。

**Comment by naokits** [comment]
返信おそくなりまして、申し訳ありません。

了解しました。
