### ISSUE TITLE
init処理のついか

### ISSUE THREAD

**Issue by Akira-Taniguchi** [techbureau/zaifbot#15]
zaifbotはsqliteにデータを保存しています。
なので、動作時にテーブルが存在しない場合、テーブルをクリエイトする処理を行っています。

あまりスマートな方法ではないので、init処理を作成し、そのタイミングでテーブルを作成するようにしましょう。

実行イメージ
１．virtualenv zaif_bot_venv
２．source zaif_bot_venv/bin/activate
３．(zaif_bot_venv)pip install zaifbot
//zaifbotをインストールした環境で「init_datebase」コマンドを実行すると、sqliteにテーブルが作成される
４．(zaif_bot_venv)init_datebase           

コマンドに関してはsetup.pyのentry_pointsやconsole_scriptsを調べるとわかると思います。

**Comment by RossyWhite** [comment]
終了したのでクローズします。
