### ISSUE TITLE
Wikiのドキュメントのお手伝いさせていただこうと思います。

### ISSUE THREAD

**Issue by ntapp** [techbureau/zaifbot#167]
現状、ほとんど嘘ばっかりになっているので、ドキュメントの調整のお手伝いをさせていただこうと思います。

**Comment by ntapp** [comment]
母の入院などでバタバタしていて、ご連絡遅くなりました。
何かありましたらまたご連絡ください。

ドキュメントが充実しててびっくりしました :)。

2017-07-31 16:58 GMT+08:00 RossyWhite <notifications@github.com>:

**Comment by RossyWhite** [comment]
かなり突貫工事ですので、間違っていたらお気軽におっしゃってください。

**Comment by ntapp** [comment]
了解しました。よろしくお願いします。

2017-08-03 14:03 GMT+08:00 RossyWhite <notifications@github.com>:
