### ISSUE TITLE
[質問] DjangoやFlaskなどでの利用は想定されているでしょうか？

### ISSUE THREAD

**Issue by ntapp** [techbureau/zaifbot#203]
0.0.5については未検証なのですが、0.0.4においては zaifbotをimportするだけでローカルサーバが起動しないという症状がでていました。

**Comment by RossyWhite** [comment]
現状全く想定していません。

その問題については、[Bug report](https://github.com/techbureau/zaifbot/issues/new?title=%5BBug%5D&labels=bug&body=%23%23%23%23+Summary+%0A%0A%23%23%23%23+Your+Environment+%0A%0A%23%23%23%23+Steps+to+reproduce+the+issue+%0A%0A%23%23%23%23+What%27s+the+expected+result%3F+%0A%0A%23%23%23%23+What%27s+the+actual+result%3F+%0A%0A%23%23%23%23+Solution+%0A%0A%3C!--+If+you+have+-!%3E)下されば見てみます。

**Comment by ntapp** [comment]
承知しました。
では、0.0.5で実験してみた結果、問題があれば別issueに上げさせていただきます。


2017-08-03 14:42 GMT+08:00 RossyWhite <notifications@github.com>:

**Comment by RossyWhite** [comment]
お手数おかけします。

**Comment by RossyWhite** [comment]
さっき0.0.6になったので、そちらで検証されると良いかと思います。

**Comment by ntapp** [comment]
@RossyWhite 了解しました。今、軽く検証中です。

```
(venv) ➜  zaifbot-demo git:(develop) ✗ pip3 show zaifbot
Name: zaifbot
Version: 0.0.6
Summary: trading bot framework for zaif exchange
Home-page: https://github.com/techbureau/zaifbot
Author: AkiraTaniguchi DaikiShiroi Monji
Author-email: a.taniguchi@techbureau.jp daikishiroi@gmail.com
License: MIT
Location: /Users/naokits/github/zaifbot-demo/venv/lib/python3.6/site-packages
Requires: SQLAlchemy, slackclient, pytz, requests, slack-logger, zaifapi, numpy, pandas, websocket-client
```
