### ISSUE TITLE
[質問] init_databaseによって作成されるDBファイルの場所について

### ISSUE THREAD

**Issue by ntapp** [techbureau/zaifbot#205]
@rhosoi 

`init_database` コマンドによって作成されるDBファイルの保存場所を指定できるようにする予定は無いでしょうか？

```
(venv) ➜  zaifbot-demo git:(develop) ✗ find ./ -name zaifbot.db
.//venv/lib/python3.6/site-packages/zaifbot/db/zaifbot.db
```

**Comment by rhosoi** [comment]
すいません、このリポジトリわたくし触ってないのでよくわかってないのです(´∀｀)

**Comment by RossyWhite** [comment]
優先度低いのでやってないだけです。
プルリクエストdev-0.0.7もらえればマージします。

何なら別のデータベースにも対応できるようにしてくだされば最高です。

**Comment by ntapp** [comment]
@RossyWhite 

特に急ぎはしておりませんので、予定を伺いました。

> 何なら別のデータベースにも対応できるようにしてくだされば最高です。

zaifbotライブラリがWSGI環境で利用できることが確認できたら、考えてみるかもしれません。

ちょっと話がずれますが、 TA-Libさえ使ってなければ、IBMのBluemixやGoogle Platformでも使えるのになと思います。ですので、TA-Libを使わないインジケータ処理の方に興味があります。

一応フォークはしました。
よろしくお願いします。

**Comment by ntapp** [comment]
@rhosoi 了解しました。失礼しました。

**Comment by RossyWhite** [comment]
> ちょっと話がずれますが、 TA-Libさえ使ってなければ、IBMのBluemixやGoogle Platformでも使えるのになと思います。ですので、TA-Libを使わないインジケータ処理の方に興味があります。

同感です。
ただ独自実装だと可読性が落ちるし、検証も難しいと思ったので現状TA-Libに落ち着いています。
もし今後もっと良いライブラリ等があれば入れ替えを検討するかもしれません。

@ntapp
