### ISSUE TITLE
v0.0.7 Bug list

### ISSUE THREAD

**Issue by RossyWhite** [techbureau/zaifbot#220]
* ログでパーミッションエラーが出る可能性がある(windowsで確認済み。動作に影響はなし)

> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:

**Comment by RossyWhite** [comment]
> ログでパーミッションエラーが出る可能性がある(windowsで確認済み。動作に影響はなし)
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:

修正済み。v0.0.8で反映されます。

**Comment by RossyWhite** [comment]
#221

**Comment by RossyWhite** [comment]
#223

**Comment by ntapp** [comment]
時々 `ZaifApiNonceError` が発生します。ずっと走らせていると、いつの間にかこのエラーが出ている状態なので、どのような状況で発生しているかは不明です。

**Comment by RossyWhite** [comment]
@ntapp 
> 時々 ZaifApiNonceError が発生します。ずっと走らせていると、いつの間にかこのエラーが出ている状態なので、どのような状況で発生しているかは不明です。

https://github.com/techbureau/zaifapi/pull/4 で修正されたかと思います。
どうでしょうか？

**Comment by ntapp** [comment]
@RossyWhite 
対応ありがとうございます。今のところ、エラーは発生しません。

**Comment by RossyWhite** [comment]
👍

**Comment by ntapp** [comment]
@RossyWhite 
MACDが１件しか返らない場合があります。

```python
macds = MACD(currency_pair='ZAIF_jpy', period='5m', short=12, long=26, signal=9).request_data(count=2, to_epoch_time=time.time())
print(macds)
```

上記のコードをEntryを継承したクラス内で使用しているのですが、通常は正常に２件データが返ってきますが、時々１件しか返らない場合が有ります。

```
{'time': 1504353900000, 'macd': 0.0051053333936390555, 'macdsignal': 0.006358988706053682, 'macdhist': -0.0012536553124146265}
```

ご確認と対応をお願いします。

**Comment by RossyWhite** [comment]
timestampの件と合わせて確認いたしますね:)
できれば、次から別のissueを作っていただき報告してもらえると大変助かります。

**Comment by RossyWhite** [comment]
@ntapp 
> MACDが１件しか返らない場合があります。

チャートがtimestampベースでしか取得できないため、
実行のタイミングが悪ければcountがずれる可能性がありました。

あまりやりたくない処理ですが、countがおかしい時は少し待つようにしましたので、
とりあえずはcountずれでbotが途中で止まったりはしなくなるかと思います。

v0.0.8で反映されるかと思われます。

**Comment by ntapp** [comment]
@RossyWhite 

毎度対応ありがとうございます。最近時間が取れないので、また確認したいと思います。

**Comment by RossyWhite** [comment]
0.0.8がリリースしたので、次から何かあればそちらでお願いします。
