### ISSUE TITLE
[Bug] btc/jpy取引でinvalid price parameterが発生する

### ISSUE THREAD

**Issue by zfhrp6** [techbureau/zaifbot#221]
#### Summary 
チュートリアルのコードにおいて，XEM/JPYでなくBTC/JPYの取引を行うとZaifApiError(invalid price parameter)により停止する

#### Your Environment 
zaifapi          1.5.5      
zaifbot          0.0.7      

#### Steps to reproduce the issue 
チュートリアルにおいて，xem_jpyの指定をbtc_jpyに変更する

#### What's the expected result? 
設定したルールに従って取引が行われる

#### What's the actual result? 
ZaifApiErrorの発生によりbotが停止する

#### Solution 
通貨ペアごとの最小取引単位および整数/小数の制御を入れる

**Comment by RossyWhite** [comment]
@zfhrp6 報告ありがとうございます！
btc高いので見てませんでした、、
確認して直しておきます。

**Comment by RossyWhite** [comment]
こちら修正する余裕は今ないですが、原因だけ、、

btc_jpyの場合、  
last_priceでbtc_jpyを取得したときは383823.0という風にfloatで値が返りますが、  
tradeメソッドでは、btc_jpyでfloatでpriceを入力できないというzaifのapiの仕様から来ています。

落ち着きましたら、修正しますので、、、

**Comment by RossyWhite** [comment]
修正させていただきました。
v0.0.8で反映されるかと思われます。
