### ISSUE TITLE
［優先度高］［要望］privateAPIのactive_ordersが現在有効な注文が無い場合Noneを返す

### ISSUE THREAD

**Issue by ttskmnj** [techbureau/zaifbot#27]
現在有効な注文がある場合は配列で注文一覧を返すのですが、有効な注文が無い場合にNoneを返してきます。
返り値のタイプが違うのはよく無いので、他の関数にも合わせて空の配列を返す様に修正お願いします。

**Comment by RossyWhite** [comment]
自分の環境では問題なさげなのですが、もしかしてこれもう解決していますか？

**Comment by ttskmnj** [comment]
from zaifbot.bot_common.api.wrapper import BotTradeApi

api_key = ''
api_secret = ''

bot_trade_api = BotTradeApi(api_key, api_secret)
active_orders = bot_trade_api.active_orders(currency_pair='btc_jpy')
print(active_orders)

api_keyとapi_secretを入れて、発注が無い状態で試してもらっていいですか？

**Comment by ttskmnj** [comment]
from zaifbot.bot_common.api.wrapper import BotTradeApi

api_key = ''
api_secret = ''

bot_trade_api = BotTradeApi(api_key, api_secret)
active_orders = bot_trade_api.active_orders(currency_pair='btc_jpy')
print(active_orders)

有効な注文がある場合と無い場合でこのテストコード試してもらっていいですか。

**Comment by RossyWhite** [comment]
### 注文がある時

{'200468518': {'currency_pair': 'btc_jpy', 'action': 'bid', 'amount': 0.01, 'price': 150000.0, 'timestamp': '1494422154', 'comment': ''}, '200466350': {'currency_pair': 'btc_jpy', 'action': 'bid', 'amount': 0.01, 'price': 150000.0, 'timestamp': '1494422008', 'comment': ''}}

### 注文がない時

{}

こんな感じでした。Noneはかえってこないです、、

**Comment by ttskmnj** [comment]
すみません。
仮想環境作り直したら治りました。
