### ISSUE TITLE
［優先度高］［バグ］actiuve_ordersの戻り値がおかしい

### ISSUE THREAD

**Issue by Akira-Taniguchi** [techbureau/zaifbot#30]
>BotBotTradeApiのactiuve_ordersなぜか今回は有効な注文があってもNoneを返す様になってました。先週試した時は有効な注文がある時は、有効な注文一覧を配列で返してたんですけど。ちょっと見てもらっていいですか。

とのこと

他のメソッドも見ておいてください。

**Comment by RossyWhite** [comment]
このissue他とかぶってるので閉じます。
