### ISSUE TITLE
［優先度高］［バグ］［RossyWhite］get_macdのsignalの計算方法が間違っている

### ISSUE THREAD

**Issue by ttskmnj** [techbureau/zaifbot#63]
EMAの算出方法が間違っています。
期間を９で５件のsignalを算出するには、１件目の前回値取得のため９件多めにMACDが必要です。
下記のページを参考にしてみてください。
http://www.iexplain.org/ema-how-to-calculate/
http://www.cam.hi-ho.ne.jp/invest/AlexanderElder/Exponential_Moving_Average.html

**Comment by ttskmnj** [comment]
毎度言葉足らずですみません。
期間を９で５件のsignalを算出するには、
k＝2 /（9＋1）
EMA＝（1ーk）* EMA前回値 + k * 今回の終値　
で算出しますが、
１件目のEMAを算出する際はEMA前回値がないため以下の計算式で算出します
最初のEMA前回値 = １件目の前の９件の終値のSMA
Pandasのewmですと、最初の前回値として前回の終値を使っている様です。

**Comment by RossyWhite** [comment]
ありがとうございます！
もう一回確認してみます。
