### ISSUE TITLE
［優先度中］macd, adx, rsiの置き換え

### ISSUE THREAD

**Issue by RossyWhite** [techbureau/zaifbot#84]
ドキュメント
https://github.com/mrjbq7/ta-lib/tree/master/docs

**Comment by RossyWhite** [comment]
失敗したときは' { success': 0 } を返した方がいいんですかね？

**Comment by Akira-Taniguchi** [comment]
そうね、ボリンジャーバンドとかと戻り値揃えていただければ
@RossyWhite
