### ISSUE TITLE
［優先度高］［要望］逆指値注文ができるようにする

### ISSUE THREAD

**Issue by Akira-Taniguchi** [techbureau/zaifbot#88]
`今 317775円で、318000になったら買い注文入れる、とか

[1:01] 
逆に310000円になったら売り注文入れる、とか、それが逆指値`

https://github.com/techbureau/zaifbot/wiki/%E6%B3%A8%E6%96%87%E3%81%AE%E8%87%AA%E5%8B%95%E3%82%AD%E3%83%A3%E3%83%B3%E3%82%BB%E3%83%AB

こんな感じでスレッド回して待機して、思った通りの値段になった時にtrade実行するみたいなイメージ

値段が飛び越えたりしたらどうするかとか、値段が離れてしまった時にどうするかとか
そのあたりは引数で調整できるように

**Comment by RossyWhite** [comment]
注文と同時に、損切り注文を同時に出すとかしたいですね。

http://hirose-fx.co.jp/category/order/
https://lightning.bitflyer.jp/docs/specialorder?lang=ja
